# Generated by Django 3.1.1 on 2020-09-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('completed', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
