# Generated by Django 3.1.1 on 2020-09-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
